# Generated by Django 5.2.16 on 2026-07-31 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="имя")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="компания"
                    ),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=120, verbose_name="сфера"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="почта"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="Красноярск",
                        max_length=80,
                        verbose_name="город",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Без @. Нужен, чтобы выдать доступ в закрытый клуб.",
                        max_length=64,
                        verbose_name="telegram",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="telegram ID"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активный"),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="имя"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="телефон"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="сфера бизнеса"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="telegram"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("form", "Форма на сайте"),
                            ("audit", "Экспресс-проверка файла"),
                            ("club", "Заявка в клуб"),
                        ],
                        default="form",
                        max_length=16,
                        verbose_name="источник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("contacted", "Связались"),
                            ("meeting", "Разбор назначен"),
                            ("proposal", "Отправлено предложение"),
                            ("won", "Взяли в работу"),
                            ("lost", "Отказ"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "delivered_to_telegram",
                    models.BooleanField(default=False, verbose_name="ушла в Telegram"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="landing.client",
                        verbose_name="клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="сумма, ₽"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("project", "Система под ключ"),
                            ("club", "Подписка на клуб"),
                            ("other", "Другое"),
                        ],
                        default="project",
                        max_length=16,
                        verbose_name="назначение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Оплачено"),
                            ("canceled", "Отменена"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="manual",
                        help_text="manual — перевод или счёт, yookassa — эквайринг",
                        max_length=32,
                        verbose_name="способ",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="ID у провайдера",
                    ),
                ),
                (
                    "payer_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="телефон плательщика"
                    ),
                ),
                (
                    "payer_telegram",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="telegram плательщика"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="оплачено"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="комментарий"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="landing.client",
                        verbose_name="клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "оплата",
                "verbose_name_plural": "оплаты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ClubSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("month", "Месяц"),
                            ("quarter", "Три месяца"),
                            ("year", "Год"),
                            ("gift", "Доступ клиента (бесплатно)"),
                        ],
                        default="month",
                        max_length=16,
                        verbose_name="тариф",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ждёт оплаты"),
                            ("active", "Активна"),
                            ("expired", "Истекла"),
                            ("canceled", "Отменена"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="цена, ₽",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="начало"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="окончание"
                    ),
                ),
                (
                    "invite_link",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="ссылка-приглашение"
                    ),
                ),
                (
                    "invite_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="приглашение выдано"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_subscriptions",
                        to="landing.client",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_subscription",
                        to="landing.payment",
                        verbose_name="оплата",
                    ),
                ),
            ],
            options={
                "verbose_name": "подписка на клуб",
                "verbose_name_plural": "подписки на клуб",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                ("title", models.CharField(max_length=160, verbose_name="название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="цена, ₽",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovery", "Разбор процессов"),
                            ("proposal", "Смета согласуется"),
                            ("build", "Сборка"),
                            ("support", "Запущен, месяц сопровождения"),
                            ("done", "Завершён"),
                            ("frozen", "Заморожен"),
                        ],
                        default="discovery",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateField(blank=True, null=True, verbose_name="начали"),
                ),
                (
                    "launched_at",
                    models.DateField(blank=True, null=True, verbose_name="запустили"),
                ),
                ("note", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="landing.client",
                        verbose_name="клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "проект",
                "verbose_name_plural": "проекты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="landing.project",
                verbose_name="проект",
            ),
        ),
    ]
