# Generated by Django 5.2.16 on 2026-08-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("form", "Форма на сайте"),
                    ("survey", "Разбор процессов"),
                    ("club", "Заявка в клуб"),
                ],
                default="form",
                max_length=16,
                verbose_name="источник",
            ),
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="имя"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, verbose_name="телефон"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="telegram"
                    ),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="ответы")),
                (
                    "allow_stories",
                    models.BooleanField(
                        default=False,
                        help_text="Согласие использовать ответы в примерах без имени и контактов",
                        verbose_name="разрешил обезличенные примеры",
                    ),
                ),
                (
                    "delivered_to_telegram",
                    models.BooleanField(default=False, verbose_name="ушёл в Telegram"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys",
                        to="landing.lead",
                        verbose_name="заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "разбор процессов",
                "verbose_name_plural": "разборы процессов",
                "ordering": ("-created_at",),
            },
        ),
    ]
