# Generated by Django 5.2.16 on 2026-08-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_alter_lead_source_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubsubscription",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Чтобы не напомнить дважды за один срок",
                null=True,
                verbose_name="напоминание отправлено",
            ),
        ),
    ]
