# Generated by Django 5.2.16 on 2026-08-20 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_clubsubscription_reminded_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_card",
                to=settings.AUTH_USER_MODEL,
                verbose_name="вход в кабинет",
            ),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="номер")),
                ("title", models.CharField(max_length=120, verbose_name="этап")),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="что здесь происходит"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Не начат"),
                            ("running", "В работе"),
                            ("review", "На согласовании"),
                            ("done", "Готово"),
                        ],
                        default="waiting",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                (
                    "waiting_on",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("me", "За мной"), ("client", "Жду вас")],
                        default="",
                        max_length=8,
                        verbose_name="кого ждём",
                    ),
                ),
                (
                    "planned_days",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="план, рабочих дней"
                    ),
                ),
                (
                    "started_at",
                    models.DateField(blank=True, null=True, verbose_name="начат"),
                ),
                (
                    "finished_at",
                    models.DateField(blank=True, null=True, verbose_name="завершён"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="landing.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "этап",
                "verbose_name_plural": "этапы",
                "ordering": ("project", "number"),
            },
        ),
        migrations.CreateModel(
            name="StageTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                ("title", models.CharField(max_length=250, verbose_name="что сделать")),
                ("comment", models.TextField(blank=True, verbose_name="пояснение")),
                (
                    "who",
                    models.CharField(
                        choices=[
                            ("me", "За мной"),
                            ("client", "За вами"),
                            ("both", "Вместе"),
                        ],
                        default="me",
                        max_length=8,
                        verbose_name="кто делает",
                    ),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="сделано")),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="когда сделано"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="порядок"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="landing.stage",
                        verbose_name="этап",
                    ),
                ),
            ],
            options={
                "verbose_name": "задача этапа",
                "verbose_name_plural": "задачи этапа",
                "ordering": ("is_done", "order", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="uniq_stage_number"
            ),
        ),
    ]
