# Generated by Django 5.2.16 on 2026-08-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0004_client_user_stage_stagetask_stage_uniq_stage_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("form", "Форма на сайте"),
                    ("survey", "Разбор процессов"),
                    ("club", "Заявка в клуб"),
                    ("build", "Собрал в конструкторе"),
                ],
                default="form",
                max_length=16,
                verbose_name="источник",
            ),
        ),
    ]
