# Generated by Django 5.2.16 on 2026-08-20 17:31

import django.db.models.deletion
import landing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0005_alter_lead_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "author_name",
                    models.CharField(max_length=120, verbose_name="имя автора"),
                ),
                (
                    "author_is_owner",
                    models.BooleanField(default=False, verbose_name="от исполнителя"),
                ),
                ("text", models.TextField(blank=True, verbose_name="текст")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="прочитано другой стороной"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="landing.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "переписка",
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=landing.models.chat_upload_to, verbose_name="файл"
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="имя файла")),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="размер, байт"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="landing.message",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл в переписке",
                "verbose_name_plural": "файлы в переписке",
                "ordering": ("pk",),
            },
        ),
    ]
