# Generated by Django 5.2.16 on 2026-08-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0006_message_messagefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lost_reason",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="причина отказа"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="note",
            field=models.TextField(blank=True, verbose_name="заметки после разговора"),
        ),
        migrations.AddField(
            model_name="lead",
            name="remind_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="напомнить"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="напоминание отправлено"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="поправлено"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("contacted", "Связались"),
                    ("meeting", "Разбор назначен"),
                    ("proposal", "Отправлено предложение"),
                    ("thinking", "Думает"),
                    ("won", "Взяли в работу"),
                    ("lost", "Отказ"),
                ],
                db_index=True,
                default="new",
                max_length=16,
                verbose_name="статус",
            ),
        ),
    ]
