# Generated by Django 5.2.16 on 2026-08-21 11:56

import django.db.models.deletion
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0007_lead_lost_reason_lead_note_lead_remind_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=250, verbose_name="адрес"),
        ),
        migrations.AddField(
            model_name="client",
            name="inn",
            field=models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="client",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="ИП Иванов Иван Иванович · ООО «Ромашка» · Иванов Иван Иванович",
                max_length=250,
                verbose_name="наименование для договора",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="signer",
            field=models.CharField(
                blank=True,
                help_text="«директора Иванова И. И.» — в родительном падеже, как это стоит в договоре после слов «в лице».",
                max_length=160,
                verbose_name="кто подписывает",
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                ("number", models.CharField(max_length=32, verbose_name="номер")),
                ("date", models.DateField(verbose_name="дата")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("issued", "Выставлен на подписание"),
                            ("signed", "Подписан"),
                            ("canceled", "Отменён"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(max_length=200, verbose_name="название системы"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="сумма, ₽",
                    ),
                ),
                (
                    "prepay_percent",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="аванс, %"
                    ),
                ),
                (
                    "term_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="срок, рабочих дней"
                    ),
                ),
                (
                    "warranty_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="гарантия, дней"
                    ),
                ),
                (
                    "support_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="сопровождение, дней"
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        blank=True,
                        help_text="Приложение № 1. По строке на блок.",
                        verbose_name="состав системы",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        blank=True, default=list, verbose_name="текст договора"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="подставленные данные"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="выставлен"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="подписан"
                    ),
                ),
                (
                    "signed_file",
                    models.FileField(
                        blank=True,
                        upload_to=landing.models.contract_upload_to,
                        verbose_name="подписанный скан",
                    ),
                ),
                (
                    "signed_name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="имя файла"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="landing.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "договор",
                "verbose_name_plural": "договоры",
                "ordering": ("-created_at",),
            },
        ),
    ]
