# Generated by Django 5.2.16 on 2026-08-21 12:12

import django.db.models.deletion
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0008_client_address_client_inn_client_legal_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Латиницей: адрес страницы работы.",
                        max_length=60,
                        unique=True,
                        verbose_name="адрес",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="как обращаться"),
                ),
                (
                    "role",
                    models.CharField(max_length=160, verbose_name="чем занимается"),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        help_text="Без https:// — оно добавится само.",
                        max_length=160,
                        verbose_name="сайт",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="город"),
                ),
                (
                    "term",
                    models.CharField(blank=True, max_length=60, verbose_name="срок"),
                ),
                (
                    "term_note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="что было со сроком"
                    ),
                ),
                (
                    "lede",
                    models.TextField(blank=True, verbose_name="одна строка о деле"),
                ),
                (
                    "was_text",
                    models.TextField(
                        blank=True,
                        help_text="По строке на пункт. Словами заказчика, а не «оптимизация бизнес-процессов»: читатель узнаёт себя именно в них.",
                        verbose_name="было",
                    ),
                ),
                (
                    "now_text",
                    models.TextField(
                        blank=True,
                        help_text="По строке на пункт.",
                        verbose_name="стало",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="порядок"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снятая с публикации работа остаётся в кабинете, но исчезает с сайта.",
                        verbose_name="показывать на сайте",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Необязательно. Связь нужна, чтобы видеть, из какой работы выросла эта страница.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="works",
                        to="landing.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "работа в портфолио",
                "verbose_name_plural": "портфолио",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="WorkFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                ("label", models.CharField(max_length=120, verbose_name="подпись")),
                ("value", models.CharField(max_length=60, verbose_name="значение")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="порядок"
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_rows",
                        to="landing.work",
                        verbose_name="работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "число в работе",
                "verbose_name_plural": "числа в работе",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="WorkShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="порядок"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=landing.models.work_upload_to,
                        verbose_name="снимок",
                    ),
                ),
                (
                    "static_name",
                    models.CharField(
                        blank=True,
                        help_text="Для снимков, лежащих в landing/static/landing/img/cases/. Без расширения: рядом должны быть имя.webp и имя-sm.webp.",
                        max_length=120,
                        verbose_name="имя файла в статике",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shot_rows",
                        to="landing.work",
                        verbose_name="работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "снимок работы",
                "verbose_name_plural": "снимки работы",
                "ordering": ("order", "pk"),
            },
        ),
    ]
