# Generated by Django 5.2.16 on 2026-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0010_works_from_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Снятая с публикации работа остаётся в кабинете, но исчезает с сайта.",
                verbose_name="показывать на сайте",
            ),
        ),
    ]
