# Generated by Django 5.2.16 on 2026-08-21 12:21

import django.db.models.deletion
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0011_alter_work_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=landing.models.attachment_upload_to,
                        verbose_name="файл",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="имя файла")),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="размер, байт"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="что это"
                    ),
                ),
                (
                    "from_client",
                    models.BooleanField(default=False, verbose_name="от заказчика"),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="кто добавил"
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="landing.lead",
                        verbose_name="заявка",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="landing.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл",
                "verbose_name_plural": "файлы",
                "ordering": ("-created_at", "-pk"),
            },
        ),
    ]
