# Generated by Django 5.2.16 on 2026-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0012_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="build_blocks",
            field=models.JSONField(
                blank=True, default=list, verbose_name="состав системы"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="build_scale",
            field=models.CharField(blank=True, max_length=16, verbose_name="масштаб"),
        ),
        migrations.AddField(
            model_name="project",
            name="build_blocks",
            field=models.JSONField(
                blank=True, default=list, verbose_name="состав системы"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="build_scale",
            field=models.CharField(blank=True, max_length=16, verbose_name="масштаб"),
        ),
    ]
