"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import unquote, urlsplit
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Читаем .env ЯВНО, указывая путь. Без вызова load_dotenv файл просто не
# читается, а всё вокруг продолжает работать на значениях по умолчанию —
# и это незаметно до первого «почему не приходят уведомления».
# Путь указан явно, потому что без него dotenv ищет файл от текущей папки,
# а команды на сервере запускаются откуда придётся.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Берем секретный ключ из .env (с фоллбэком)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

DEBUG = os.getenv('DEBUG', 'True') == 'True'

# --- Контакты сайта (используются в шаблонах и в политике конфиденциальности) ---
SITE_OWNER = os.getenv('SITE_OWNER', 'Глухов Антон Сергеевич')
SITE_PHONE = os.getenv('SITE_PHONE', '+79954412021')
SITE_PHONE_PRETTY = os.getenv('SITE_PHONE_PRETTY', '+7 (995) 441-20-21')
SITE_EMAIL = os.getenv('SITE_EMAIL', 'glukhovas@yandex.ru')
SITE_CITY = os.getenv('SITE_CITY', 'Красноярск')
SITE_HOST = os.getenv('SITE_HOST', 's-poryadok.ru')  # для ссылок в письмах и Telegram
SITE_REGION = os.getenv('SITE_REGION', 'Красноярский край')
SITE_TELEGRAM = os.getenv('SITE_TELEGRAM', '')       # ник без @, для кнопки «написать»
SITE_INN = os.getenv('SITE_INN', '382800965145')     # ИНН — подставится в политику
# Налоговый статус. Паспорт и СНИЛС здесь не нужны и на сайт не выносятся.
SITE_STATUS = os.getenv(
    'SITE_STATUS',
    'самозанятый, налог на профессиональный доход')

# --- Реквизиты для договора ---
# Здесь то, чего нет и не должно быть на сайте: адрес для писем и счёт.
# Договор без них собрать можно, выставить — нельзя: заказчик получит
# документ, распечатает, подпишет и только тогда спросит, куда платить.
CONTRACT_ADDRESS = os.getenv('CONTRACT_ADDRESS', '')   # адрес для писем
CONTRACT_ACCOUNT = os.getenv('CONTRACT_ACCOUNT', '')   # расчётный счёт
CONTRACT_BANK = os.getenv('CONTRACT_BANK', '')         # название банка
CONTRACT_BIK = os.getenv('CONTRACT_BIK', '')           # БИК
CONTRACT_CORR = os.getenv('CONTRACT_CORR', '')         # корреспондентский счёт
# Карта — для тех, кто работает без расчётного счёта. В договор попадает,
# только если счёта нет: два способа оплаты в одном документе означают
# два разных места, куда могут прийти деньги.
CONTRACT_CARD = os.getenv('CONTRACT_CARD', '')

# --- Telegram ---
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')
# ID закрытого канала (обычно вида -100...). Бот должен быть в нём администратором
# с правом приглашать по ссылке.
TELEGRAM_CLUB_CHAT_ID = os.getenv('TELEGRAM_CLUB_CHAT_ID')

# Имя бота без @ — его требует виджет входа через Telegram. Домен сайта
# должен быть привязан к боту у @BotFather (команда /setdomain), иначе
# виджет не отрисуется.
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME', '')

# Секрет для приёма сообщений бота. Придумывается один раз, любая длинная
# строка без пробелов. Ставится и в адрес обработчика, и в заголовок,
# которым Telegram подписывает каждый запрос.
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET', '')

# --- Эквайринг ЮKassa. Пока пусто — сайт работает в режиме заявок. ---
# GetPlatinum. Адрес свой у каждого аккаунта: https://ИМЯ.getplatinum.ru/api/public/pay
GETPLATINUM_API_KEY = os.getenv('GETPLATINUM_API_KEY')
GETPLATINUM_BASE_URL = os.getenv('GETPLATINUM_BASE_URL')
# Достаточно указать что-то одно: либо полный адрес выше, либо просто имя
# аккаунта — оно видно в адресной строке личного кабинета GetPlatinum.
GETPLATINUM_ACCOUNT = os.getenv('GETPLATINUM_ACCOUNT')
# Отвергать уведомления с неверной подписью. Включать только после того,
# как подпись подтвердилась настоящим уведомлением: пример в документации
# GetPlatinum противоречив. Подробности — в landing/services/getplatinum.py.
GETPLATINUM_STRICT_CHECKSUM = os.getenv('GETPLATINUM_STRICT_CHECKSUM', 'False') == 'True'

YOOKASSA_SHOP_ID = os.getenv('YOOKASSA_SHOP_ID')
YOOKASSA_SECRET_KEY = os.getenv('YOOKASSA_SECRET_KEY')

# --- Аналитика ---
YANDEX_METRIKA_ID = os.getenv('YANDEX_METRIKA_ID', '')

ALLOWED_HOSTS = ['s-poryadok.ru', 'www.s-poryadok.ru', '159.194.230.39']

if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['https://s-poryadok.ru', 'https://www.s-poryadok.ru']

# Загружаемые файлы разбираем в памяти и не сохраняем на диск.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Включайте только после того, как сайт открылся и вы убедились,
    # что сервер передаёт заголовок X-Forwarded-Proto. Иначе — цикл редиректов.
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS запоминается браузером надолго и откатывается тяжело —
    # включайте, когда https работает стабильно: HSTS_SECONDS=31536000
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Наше приложение:
    'landing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# Куда уводить незалогиненного и куда возвращать после входа. Обе точки —
# одна и та же дверь кабинета: развилка по роли живёт внутри неё.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'cabinet'
LOGOUT_REDIRECT_URL = 'index'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'landing.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ── База ─────────────────────────────────────────────────────────────
#
# По умолчанию SQLite: локально он не требует ничего ставить, а для
# разработки и тестов быстрее любого сервера.
#
# На боевом сервере — PostgreSQL, и включается он одной строкой в .env:
#
#     DATABASE_URL=postgres://poryadok:пароль@localhost:5432/poryadok
#
# Почему не SQLite на бою. Он пишет с блокировкой всей базы: пока идёт
# одна запись, остальные ждут. Пока клиентов двое, это незаметно; когда
# в кабинете сидят несколько человек и кто-то отправляет файл, остальные
# упираются в паузу. Проявляется это не отказом, а «сайт задумался», —
# и причину ищут где угодно, только не в базе.
#
# Второе, важнее: SQLite — один файл, и восстановление всегда «откатить
# всё целиком на момент копии». У PostgreSQL есть журнал, и вернуться
# можно на конкретную минуту.

def _database_from(url):
    """Разобрать DATABASE_URL. Возвращает None, если адреса нет.

    Свой разбор вместо библиотеки: строка одна, формат известен, а
    лишняя зависимость на сервере — это ещё одна вещь, которая однажды
    не поставится в самый неподходящий момент.
    """
    if not url:
        return None

    parts = urlsplit(url)
    if parts.scheme not in ('postgres', 'postgresql'):
        raise ImproperlyConfigured(
            f'DATABASE_URL: не понимаю «{parts.scheme}». '
            'Ожидается postgres:// или postgresql://')

    name = unquote(parts.path.lstrip('/'))
    if not name:
        raise ImproperlyConfigured('DATABASE_URL: не указано имя базы.')

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': name,
        # Пароль в адресе бывает с символами, которые сами по себе
        # что-то значат: @ и / разрежут строку не там. В адресе они
        # закодированы, здесь — раскодируются обратно.
        'USER': unquote(parts.username or ''),
        'PASSWORD': unquote(parts.password or ''),
        'HOST': parts.hostname or 'localhost',
        'PORT': str(parts.port or 5432),
        # Соединение переиспользуется десять минут. Открывать его заново
        # на каждый запрос — это лишние миллисекунды на ровном месте,
        # а при всплеске обращений ещё и упор в лимит соединений.
        'CONN_MAX_AGE': 600,
        'CONN_HEALTH_CHECKS': True,
    }


DATABASES = {
    'default': _database_from(os.getenv('DATABASE_URL')) or {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Krasnoyarsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Путь для сборки статики
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Имена собранных файлов получают отпечаток содержимого: site.a1b2c3.css.
# Иначе nginx отдаёт статику с кэшем на 30 дней, а браузер посетителя
# продолжает показывать старые стили после каждого обновления сайта —
# и «у меня всё поехало» становится нормой. С отпечатком новый файл имеет
# новое имя, и кэш перестаёт быть проблемой.
# В разработке отпечатки только мешают: они требуют collectstatic после
# каждой правки CSS. Поэтому включаются лишь на проде.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG else
            'core.storage.ForgivingManifestStaticFilesStorage'
        ),
    },
}
STATIC_URL = '/static/'

# Файлы, которые присылают люди: вложения в переписке по проекту.
# Отдельно от статики и намеренно вне staticfiles: collectstatic
# эту папку не трогает, и чужие файлы не могут попасть в сборку.
#
# На проде их отдаёт nginx, а не Django, — см. DEPLOY.md. Сам Django
# отдаёт их только в разработке.
# Почта. Нужна ровно для одного — восстановления пароля по ссылке.
# Пока не настроена, страница восстановления честно об этом говорит
# и отправляет звонить, а не молчит и не делает вид, что письмо ушло.
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() in ('1', 'true', 'yes')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or SITE_EMAIL)
# В разработке письма печатаются в консоль: настоящий SMTP локально
# не нужен, а увидеть письмо целиком — нужно.
EMAIL_BACKEND = ('django.core.mail.backends.console.EmailBackend' if DEBUG
                 else 'django.core.mail.backends.smtp.EmailBackend')

# Настроена ли почта на самом деле. По этому флагу страница входа решает,
# показывать ли «Забыли пароль?»: ссылка, ведущая в тупик, хуже её
# отсутствия — человек нажмёт, ничего не получит и решит, что сломалось
# всё, а не одна кнопка.
EMAIL_READY = bool(EMAIL_HOST and EMAIL_HOST_USER) or DEBUG

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Больше этого через форму не пройдёт. Двадцать мегабайт — это макет
# в PDF и десяток фотографий; видео здесь не место, для него есть
# ссылка. Такой же предел стоит в nginx: без него запрос отвергается
# уже на входе, и Django об этом не узнаёт.
MAX_UPLOAD_SIZE = 20 * 1024 * 1024

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Логи: сбои доставки заявок должны быть видны, а не теряться.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {'format': '{asctime} {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'plain'},
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'maxBytes': 2 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'plain',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'landing': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
    },
}
(BASE_DIR / 'logs').mkdir(exist_ok=True)
